import { DiscordStyleId } from "../types/style-ids";

export const defaultDiscordMapping: Record<DiscordStyleId, string> = {
  "action-default": "latte-med",
  "action-hover": "latte-thick",
  "nav-item-bg": "black-glass",
  "nav-item-active": "latte-thin",
  "nav-indicator": "latte",
  separator: "Brd",
  "text-default": "smoke-thick",
  "container-bg": "black-glass",
  "tooltip-bg": "black-glass",
  "hover-bg": "graphite-thin",
  "active-bg": "graphite-med",
  // Server-specific mappings
  "server-header-bg": "black-glass",
  "server-header-hover": "graphite-thin",
  "server-header-border": "Brd",
  "dropdown-bg": "black-glass",
  "dropdown-item-hover": "graphite-glass",
  "dropdown-text": "smoke-thick",
  "invite-text": "latte-med",
  "danger-text": "latte-thick",
  "icon-moderator": "latte-med",
  "icon-admin": "latte-thick",
  "channel-item-active": "graphite-med",
  "channel-item-bg": "black-glass",
  "icon-default": "smoke-thick",
  "text-active": "smoke-thick",
  "icon-muted": "smoke-thin",
  // EVOLVED: Modal-specific style mappings
  "modal-overlay": "black-glass",
  "modal-bg": "black-glass",
  "modal-border": "Brd",
  "modal-text": "smoke-thick",
  "modal-close": "smoke-thick",
  "modal-title": "smoke-thick",
  "modal-description": "smoke-med",
};
