{
    id: "xtc",
    name: "xtc",
    songCount: 3,
    thumbnail: "/media/playlists/xtc.png",
    songs: [
      {
        id: "xtc-1",
        title: "song1",
        artist: "xtcFM",
        path: "/audio/xtc/saopaulo.mp4",
        thumbnail: "/media/songs/saopaulo.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
      {
        id: "xtc-2",
        title: "song2",
        artist: "xtcFM",
        path: "/audio/xtc/timeless.mp4",
        thumbnail: "/media/songs/timeless.png",
        videoUrl: "https://www.youtube.com/watch?v=3upvj6tDHoI",
      },
      {
        id: "xtc-3",
        title: "song3",
        artist: "xtcFM",
        path: "/audio/xtc/howdeepisyourlove.mp4",
        thumbnail: "/media/songs/howdeepisyourlove.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
      {
        id: "xtc-4",
        title: "song4",
        artist: "xtcFM",
        path: "/audio/xtc/song4.mp4",
        thumbnail: "/media/songs/song4.png",
        videoUrl: "https://www.youtube.com/watch?v=h9NSpC2xE-0",
      },
      {
        id: "xtc-5",
        title: "xtra",
        artist: "xtcFM",
        path: "/audio/xtc/cursed.mp4",
        thumbnail: "/media/songs/cursed.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
      {
        id: "xtc-6",
        title: "xtra",
        artist: "xtcFM",
        path: "/audio/xtc/thehills.mp4",
        thumbnail: "/media/songs/thehills.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
      {
        id: "xtc-7",
        title: "xtra",
        artist: "xtcFM",
        path: "/audio/xtc/alldayandnight.mp4",
        thumbnail: "/media/songs/alldayandnight.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
      {
        id: "xtc-8",
        title: "xtra",
        artist: "xtcFM",
        path: "/audio/xtc/notearslefttocry.mp4",
        thumbnail: "/media/songs/notearslefttocry.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
      {
        id: "xtc-9",
        title: "xtra",
        artist: "xtcFM",
        path: "/audio/xtc/lifeline.mp4",
        thumbnail: "/media/songs/lifeline.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
      {
        id: "xtc-10",
        title: "xtra",
        artist: "xtcFM",
        path: "/audio/xtc/often.mp4",
        thumbnail: "/media/songs/often.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
      {
        id: "xtc-11",
        title: "xtra",
        artist: "xtcFM",
        path: "/audio/xtc/siai.mp4",
        thumbnail: "/media/songs/siai.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
      {
        id: "xtc-12",
        title: "xtra",
        artist: "xtcFM",
        path: "/audio/xtc/malamente.mp4",
        thumbnail: "/media/songs/malamente.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
      {
        id: "xtc-13",
        title: "xtra",
        artist: "xtcFM",
        path: "/audio/xtc/yekeyeke.mp4",
        thumbnail: "/media/songs/yekeyeke.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
      {
        id: "xtc-14",
        title: "xtra",
        artist: "xtcFM",
        path: "/audio/xtc/starboy.mp4",
        thumbnail: "/media/songs/starboy.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
      {
        id: "xtc-15",
        title: "xtra",
        artist: "xtcFM",
        path: "/audio/xtc/youright.mp4",
        thumbnail: "/media/songs/youright.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
      {
        id: "xtc-16",
        title: "xtra",
        artist: "xtcFM",
        path: "/audio/xtc/popular.mp4",
        thumbnail: "/media/songs/popular.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
      {
        id: "xtc-17",
        title: "xtra",
        artist: "xtcFM",
        path: "/audio/xtc/breakmyheart.mp4",
        thumbnail: "/media/songs/breakmyheart.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
      {
        id: "xtc-18",
        title: "xtra",
        artist: "xtcFM",
        path: "/audio/xtc/nothingislost.mp4",
        thumbnail: "/media/songs/nothingislost.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
      {
        id: "xtc-19",
        title: "xtra",
        artist: "xtcFM",
        path: "/audio/xtc/provenza.mp4",
        thumbnail: "/media/songs/provenza.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
      {
        id: "xtc-20",
        title: "xtra",
        artist: "xtcFM",
        path: "/audio/xtc/enchantedwaterfall.mp4",
        thumbnail: "/media/songs/enchantedwaterfall.png",
        videoUrl: "https://www.youtube.com/watch?v=FiE1pA_86S4",
      },
    ],
  },